### ISSUE TITLE
Broken?

### ISSUE THREAD

**Issue by theDanielJLewis** [trs/shift-code-redeemer#2]
I think this is broken. After cloning and running `npm i`, I tried both ways of running the script (`npm run redeem` in the GIF, and `npx shift-code-redeemer` in the written instructions). The latter returns the error:

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/shift-code-redeemer - Not found
npm ERR! 404
npm ERR! 404  'shift-code-redeemer@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-09-19T02_01_13_529Z-debug.log
Install for shift-code-redeemer@latest failed with code 1
```

It looks like the script is no longer on npmjs.

**Comment by trs** [comment]
Sorry, I haven't actually published this yet!
For now you can run `node src/bin.js` after cloning and installing.

**Comment by trs** [comment]
This has now been published to npm.
`npx shift-cod-redeemer` should work as expected now.

I've also added Borderlands 3 support!
